// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cleo.Data;

#nullable disable

namespace cleo.Migrations
{
    [DbContext(typeof(CleoDbContext))]
    [Migration("20260506164527_AddLogoPathToSettings")]
    partial class AddLogoPathToSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("cleo.Models.AdminMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@cleo.app",
                            IsSuperAdmin = true,
                            LastActive = new DateTime(2026, 5, 6, 16, 45, 27, 657, DateTimeKind.Utc).AddTicks(1292),
                            Name = "Admin",
                            Password = "password123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "diya@cleo.app",
                            IsSuperAdmin = true,
                            LastActive = new DateTime(2026, 5, 6, 16, 45, 27, 657, DateTimeKind.Utc).AddTicks(1296),
                            Name = "Diya",
                            Password = "password123"
                        },
                        new
                        {
                            Id = 3,
                            Email = "hensy@cleo.app",
                            IsSuperAdmin = true,
                            LastActive = new DateTime(2026, 5, 6, 16, 45, 27, 657, DateTimeKind.Utc).AddTicks(1297),
                            Name = "Hensy",
                            Password = "password123"
                        });
                });

            modelBuilder.Entity("cleo.Models.ContentArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Views")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Quick-Nutrition",
                            Content = "During your period, your body loses iron. Focus on leafy greens, lentils, and lean meats to maintain energy levels.",
                            PublishDate = new DateTime(2026, 5, 6, 16, 45, 27, 657, DateTimeKind.Utc).AddTicks(1399),
                            Status = "Published",
                            Title = "Focus on Iron-Rich Foods",
                            Views = 1240
                        },
                        new
                        {
                            Id = 2,
                            Category = "Exercise",
                            Content = "Gentle yoga poses like Child's Pose and Cat-Cow can help relax pelvic muscles and reduce menstrual cramping.",
                            PublishDate = new DateTime(2026, 5, 6, 16, 45, 27, 657, DateTimeKind.Utc).AddTicks(1401),
                            Status = "Published",
                            Title = "Yoga for Cramp Relief",
                            Views = 952
                        },
                        new
                        {
                            Id = 3,
                            Category = "Wellness",
                            Content = "The Luteinizing Hormone (LH) surge triggers ovulation. Tracking this can help you identify your most fertile days.",
                            PublishDate = new DateTime(2026, 5, 6, 16, 45, 27, 657, DateTimeKind.Utc).AddTicks(1403),
                            Status = "Published",
                            Title = "Understanding LH Surge",
                            Views = 1520
                        },
                        new
                        {
                            Id = 4,
                            Category = "PMS-Relief",
                            Content = "Reduce salt intake and stay hydrated to combat hormonal water retention during the luteal phase.",
                            PublishDate = new DateTime(2026, 5, 6, 16, 45, 27, 657, DateTimeKind.Utc).AddTicks(1403),
                            Status = "Published",
                            Title = "Managing PMS Bloating",
                            Views = 840
                        },
                        new
                        {
                            Id = 5,
                            Category = "Quick-Nutrition",
                            Content = "Magnesium-rich foods like dark chocolate and pumpkin seeds can help stabilize mood swings and reduce anxiety.",
                            PublishDate = new DateTime(2026, 5, 6, 16, 45, 27, 657, DateTimeKind.Utc).AddTicks(1404),
                            Status = "Published",
                            Title = "Magnesium for Mood",
                            Views = 620
                        },
                        new
                        {
                            Id = 6,
                            Category = "Exercise",
                            Content = "A 20-minute brisk walk increases blood flow and releases endorphins, which can alleviate low-level period pain.",
                            PublishDate = new DateTime(2026, 5, 6, 16, 45, 27, 657, DateTimeKind.Utc).AddTicks(1405),
                            Status = "Published",
                            Title = "The Power of Walking",
                            Views = 750
                        },
                        new
                        {
                            Id = 7,
                            Category = "Wellness",
                            Content = "Estrogen rises during this phase, often leading to increased energy and improved cognitive focus. It's a great time for new projects.",
                            PublishDate = new DateTime(2026, 5, 6, 16, 45, 27, 657, DateTimeKind.Utc).AddTicks(1406),
                            Status = "Published",
                            Title = "The Follicular Phase",
                            Views = 1100
                        },
                        new
                        {
                            Id = 8,
                            Category = "Hygiene",
                            Content = "Your body temperature changes throughout your cycle, which can affect sleep. Keep your room cool during the luteal phase.",
                            PublishDate = new DateTime(2026, 5, 6, 16, 45, 27, 657, DateTimeKind.Utc).AddTicks(1411),
                            Status = "Published",
                            Title = "Sleep Hygiene & Cycles",
                            Views = 430
                        },
                        new
                        {
                            Id = 9,
                            Category = "Quick-Nutrition",
                            Content = "Raspberry leaf and ginger teas are known for their ability to soothe the uterus and reduce inflammation.",
                            PublishDate = new DateTime(2026, 5, 6, 16, 45, 27, 657, DateTimeKind.Utc).AddTicks(1411),
                            Status = "Published",
                            Title = "Herbal Tea Benefits",
                            Views = 510
                        },
                        new
                        {
                            Id = 10,
                            Category = "Exercise",
                            Content = "You might feel strongest during your follicular phase. High-intensity training is often most effective during this time.",
                            PublishDate = new DateTime(2026, 5, 6, 16, 45, 27, 657, DateTimeKind.Utc).AddTicks(1412),
                            Status = "Published",
                            Title = "Strength Training Timing",
                            Views = 890
                        });
                });

            modelBuilder.Entity("cleo.Models.CycleTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Flow")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrentCycle")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CycleTracks");
                });

            modelBuilder.Entity("cleo.Models.MoodNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AITip")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mood")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MoodNotes");
                });

            modelBuilder.Entity("cleo.Models.NotificationSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DailyCheckInEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultReminderTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastDailyCheckInSentDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NewCycleSummaryEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OvulationWindowEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodApproachingDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PeriodApproachingEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("NotificationSettings");
                });

            modelBuilder.Entity("cleo.Models.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmailSent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReminderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("cleo.Models.SymptomLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AITip")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SymptomLogs");
                });

            modelBuilder.Entity("cleo.Models.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowNewRegistrations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultCycleLength")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableDiscussionDisplay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RestrictAdminAccess")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SessionTimeout")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowCycleSummaryCard")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowTimerDashboard")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowNewRegistrations = true,
                            ContactNo = "+91 1234567890",
                            DefaultCycleLength = 28,
                            EnableDiscussionDisplay = true,
                            RestrictAdminAccess = false,
                            SessionTimeout = true,
                            ShowCycleSummaryCard = false,
                            ShowTimerDashboard = false,
                            SiteName = "Cleo",
                            SupportEmail = "support@cleo.com"
                        });
                });

            modelBuilder.Entity("cleo.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgeGroup")
                        .HasColumnType("TEXT");

                    b.Property<int>("CycleLength")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastActivityDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<int>("PeriodLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
